
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Home extends ContentItem {
    public baseTitle: Elements.TextElement | undefined;
    public baseTeaserImage: Elements.AssetsElement | undefined;
    public bodyCopy: Elements.RichTextElement | undefined;
    public urlPattern: Elements.UrlSlugElement | undefined;
    public seoMetaTitle: Elements.TextElement | undefined;
    public seoMetaDescription: Elements.TextElement | undefined;
    public seoMetaKeywords: Elements.TextElement | undefined;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'base__title') {
                    return 'baseTitle';
                }
                if (elementName === 'base__teaser_image') {
                    return 'baseTeaserImage';
                }
                if (elementName === 'body_copy') {
                    return 'bodyCopy';
                }
                if (elementName === 'url_pattern') {
                    return 'urlPattern';
                }
                if (elementName === 'seo__meta_title') {
                    return 'seoMetaTitle';
                }
                if (elementName === 'seo__meta_description') {
                    return 'seoMetaDescription';
                }
                if (elementName === 'seo__meta_keywords') {
                    return 'seoMetaKeywords';
                }
                return elementName;
            })
        });
    }
}
