
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class YoutubeVideo extends ContentItem {
    public youtubeId: Elements.TextElement | undefined;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'youtube_id') {
                    return 'youtubeId';
                }
                return elementName;
            })
        });
    }
}
